#!/usr/bin/env bash

if [[ -z "$1" ]]; then
	echo "Usage: $0 <class_name>"
	exit 1
fi

class_name="${1^}"
header_guard="${1^^}_H"

if [[ -e "$class_name.cpp" ]]; then
	echo "Error: $class_name.cpp already exists"
	exit 1
fi

if [[ -e "$class_name.hpp" ]]; then
	echo "Error: $class_name.hpp already exists"
	exit 1
fi

cat <<EOF > "$class_name.cpp"
#include "$class_name.hpp"

// Default constructor
$class_name::$class_name() {}

// Copy constructor
$class_name::$class_name(const $class_name &other) {}

// Copy assignment operator overload \`=\`
$class_name &$class_name::operator=(const $class_name &other)
{
	if (this != &other)
	{
		// Copy values
	}
	return (*this);
}

// Destructor
$class_name::~$class_name()
{
	// Delete allocated memory
}
EOF

cat << EOF > "$class_name.hpp"
#ifndef $header_guard
# define $header_guard

# include <iostream>

class $class_name
{
	private:
		// private member variable

	public:
		$class_name();
		~$class_name();
		$class_name(const $class_name &other);
		$class_name &operator=(const $class_name &other);
};

#endif
EOF
